#!/usr/bin/env python3
import sys, re
def breakdown(instrings: str):
     for instring in instrings:
         newidregex = r'(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)-){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)'
         if re.match(r'^0[xX][0-9a-fA-F]+', instring):
             decimalid = int(instring, 16)
         elif re.match(newidregex, instring):
             parts = instring.split('-')
             decimalid = int(parts[2]) * 256 + int(parts[3])
         elif re.match(r'[0-9]+', instring):
             decimalid = int(instring)
         elif re.match(r'^[sS][0-9]+', instring):
             decimalid = int(instring[1:]) + 1080
         else:
             Except('unknown id format')
         print(f"Decimal: {str(decimalid)}")
         print(f"Serial#: {str(decimalid - 1080)}")
         print(f"    Hex: {hex(decimalid)}")
         hexid = hex(decimalid)[2:].zfill(4)
         part1 = hexid[:2]
         part2 = hexid[2:]
         print(f"    New: 10-32-{int(part1, 16)}-{int(part2, 16)}")
         print() 

def asset_id_to_new(asset_id):
    hexid = hex(asset_id)[2:].zfill(4)
    part1 = hexid[:2]
    part2 = hexid[2:]
    return f"10-32-{int(part1, 16)}-{int(part2, 16)}"
    
if __name__ == "__main__":
    print(asset_id_to_new(int(sys.argv[1])))
#    breakdown(sys.argv[1:])
